name: Docker_Hub


on:
  push:
    branches:
      - 'main'
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Extraccion de datos de github
        uses: actions/checkout@v2
      - name: Autenticacion en dockerhub
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.USUARIO_DOCKERHUB }}
          password: ${{ secrets.CLAVE_DOCKERHUB }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: vtt0001/newphone
